//  gamma-analyzer-3d - 3d visualization of sessions generated by gamma-analyzer
//  Copyright (C) 2017  Dag Robole
//
//  This program is free software: you can redistribute it and/or modify
//  it under the terms of the GNU General Public License as published by
//  the Free Software Foundation, either version 3 of the License, or
//  (at your option) any later version.
//
//  This program is distributed in the hope that it will be useful,
//  but WITHOUT ANY WARRANTY; without even the implied warranty of
//  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
//  GNU General Public License for more details.
//
//  You should have received a copy of the GNU General Public License
//  along with this program.  If not, see <http://www.gnu.org/licenses/>.

#include "gammaanalyzer3d.h"
#include "ui_gammaanalyzer3d.h"
#include "colorspectrum.h"
#include "gridentity.h"
#include "spectrumentity.h"
#include "scene.h"
#include <QDir>
#include <QFileDialog>
#include <QAction>
#include <QLabel>
#include <QMessageBox>
#include <QDebug>
#include <QColor>
#include <QVector3D>
#include <Qt3DCore/QEntity>
#include <Qt3DRender/QCamera>
#include <Qt3DRender/QObjectPicker>

GammaAnalyzer3D::GammaAnalyzer3D(QWidget *parent) :
    QMainWindow(parent),
    ui(new Ui::GammaAnalyzer3D)
{
    ui->setupUi(this);
    setupSignals();
}

GammaAnalyzer3D::~GammaAnalyzer3D()
{
    delete ui;
}

void GammaAnalyzer3D::setupSignals()
{
    QObject::connect(
                ui->actionExit,
                &QAction::triggered,
                this,
                &GammaAnalyzer3D::onApplicationExit);

    QObject::connect(
                ui->actionLoadDoserateScript,
                &QAction::triggered,
                this,
                &GammaAnalyzer3D::onLoadDoserateScript);

    QObject::connect(
                ui->actionOpenSession,
                &QAction::triggered,
                this,
                &GammaAnalyzer3D::onOpenSession);
}

void GammaAnalyzer3D::onApplicationExit()
{
    try
    {
        for(auto p : scenes)
            delete p.second;

        scenes.clear();

        QApplication::exit();
    }
    catch(const std::exception& e)
    {
        qDebug() << e.what();
    }
}

void GammaAnalyzer3D::onOpenSession()
{
    try
    {
        QString sessionDir = QFileDialog::getExistingDirectory(
                    this,
                    tr("Open session directory"),
                    QDir::homePath(),
                    QFileDialog::ShowDirsOnly | QFileDialog::DontResolveSymlinks);
        if(sessionDir.isEmpty())
            return;

        sessionDir = QDir::toNativeSeparators(sessionDir);

        auto it = scenes.find(sessionDir);
        if(it != scenes.end())
        {
            it->second->window->show();
            return;
        }

        Scene *scene = new Scene(QColor(27, 48, 46));

        if(QFile::exists(doserateScript))
            scene->session->loadDoserateScript(doserateScript);
        scene->session->loadPath(sessionDir);
        scene->window->setTitle(scene->session->name());

        new GridEntityXZ(0.0f, 10, 10.0f, QColor(255, 255, 255), scene->root);

        Palette::ColorSpectrum colorSpectrum(
                    scene->session->minDoserate(),
                    scene->session->maxDoserate());

        double halfX = (scene->session->maxX() - scene->session->minX()) / 2.0;
        double halfY = (scene->session->maxY() - scene->session->minY()) / 2.0;

        for(auto spec : scene->session->getSpectrumList())
        {
            QVector3D position(
                        (spec->x1() - scene->session->minX() - halfX) * 15000.0,
                        spec->altitudeStart() - scene->session->minAltitude(),
                        (spec->y1() - scene->session->minY() - halfY) * -15000.0);

            SpectrumEntity *entity = new SpectrumEntity(
                        position,
                        colorSpectrum(spec->doserate()),
                        spec,
                        scene->root);

            QObject::connect(
                        entity->picker(),
                        &Qt3DRender::QObjectPicker::pressed,
                        this,
                        &GammaAnalyzer3D::onPicked);
        }

        scene->camera->setUpVector(QVector3D(0.0, 1.0, 0.0));
        scene->camera->setPosition(QVector3D(0, 20, 100.0f));
        scene->camera->setViewCenter(QVector3D(0, 0, 0));

        scene->window->show();

        scenes[sessionDir] = scene;
    }
    catch(const std::exception& e)
    {
        qDebug() << e.what();
    }
}

void GammaAnalyzer3D::onLoadDoserateScript()
{
    try
    {
        QString scriptFileName = QFileDialog::getOpenFileName(
                    this,
                    tr("Load doserate script"),
                    QDir::homePath(),
                    tr("Lua script (*.lua)"));

        doserateScript = QDir::toNativeSeparators(scriptFileName);
        ui->lblDoserateScript->setText("Loaded doserate script: " + doserateScript);
    }
    catch(const std::exception& e)
    {
        qDebug() << e.what();
    }
}

void GammaAnalyzer3D::onPicked(Qt3DRender::QPickEvent *evt)
{
    try
    {
        if(evt->button() != Qt3DRender::QPickEvent::LeftButton)
            return;

        SpectrumEntity *entity = qobject_cast<SpectrumEntity*>(sender()->parent());
        if(!entity)
            return;

        Gamma::Spectrum *spec = entity->spectrum();

        ui->lblSpectrum->setText(
                    "Selected spectrum: " + spec->sessionName() + " " +
                    QString::number(spec->sessionIndex()));
        ui->lblLatitude->setText("Latitude: " + QString::number(spec->latitudeStart()));
        ui->lblLongitude->setText("Longitude: " + QString::number(spec->longitudeStart()));
        ui->lblAltitude->setText("Altitude: " + QString::number(spec->altitudeStart()));
        ui->lblRealtime->setText("Real time: " + QString::number(spec->realtime()));
        ui->lblDoserate->setText("Doserate: " + QString::number(spec->doserate()));
    }
    catch(const std::exception& e)
    {
        qDebug() << e.what();
    }
}
