//  gamma-analyzer-3d - 3d visualization of sessions generated by gamma-analyzer
//  Copyright (C) 2017  Dag Robole
//
//  This program is free software: you can redistribute it and/or modify
//  it under the terms of the GNU General Public License as published by
//  the Free Software Foundation, either version 3 of the License, or
//  (at your option) any later version.
//
//  This program is distributed in the hope that it will be useful,
//  but WITHOUT ANY WARRANTY; without even the implied warranty of
//  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
//  GNU General Public License for more details.
//
//  You should have received a copy of the GNU General Public License
//  along with this program.  If not, see <http://www.gnu.org/licenses/>.

#ifndef GAMMAN3D_H
#define GAMMAN3D_H

#include <QMainWindow>
#include <QtDataVisualization/Q3DScatter>
#include "session.h"

namespace Ui {
class gamman3d;
}

class gamman3d : public QMainWindow
{
    Q_OBJECT

public:
    explicit gamman3d(QWidget *parent = 0);
    ~gamman3d();

    bool initialize();
    void createMenu();
    void populateScene(QString dir);    

private:
    Ui::gamman3d *ui;
    Session *session;
    QtDataVisualization::Q3DScatter *scatter;
    QtDataVisualization::QScatter3DSeries *series;
    QtDataVisualization::QScatterDataArray *dataArray;


private slots:
    void openSession();
};

#endif // GAMMAN3D_H
