//  gamma-analyzer-3d - 3d visualization of sessions generated by gamma-analyzer
//  Copyright (C) 2017  Dag Robole
//
//  This program is free software: you can redistribute it and/or modify
//  it under the terms of the GNU General Public License as published by
//  the Free Software Foundation, either version 3 of the License, or
//  (at your option) any later version.
//
//  This program is distributed in the hope that it will be useful,
//  but WITHOUT ANY WARRANTY; without even the implied warranty of
//  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
//  GNU General Public License for more details.
//
//  You should have received a copy of the GNU General Public License
//  along with this program.  If not, see <http://www.gnu.org/licenses/>.

#ifndef GAMMAN3D_H
#define GAMMAN3D_H

#include "gui.h"
#include "session.h"
#include <QMainWindow>

class gamman3d : public QMainWindow
{
    Q_OBJECT

public:

    explicit gamman3d(QWidget *parent = 0);
    ~gamman3d();

    void setupSignals();

    void populateScene();

private:

    // FIXME: Use smart pointers (qtcreator doesn't complete them atm)
    Gui* gui;
    gamma::Session* session;

private slots:

    void openSession();
    void closeSession();    
    void resizeSceneNode(int val);
    void changeSceneTheme(int theme);
    void sceneNodeSelected(int idx);
};

#endif // GAMMAN3D_H
