//  gamma-analyzer-3d - 3d visualization of sessions generated by gamma-analyzer
//  Copyright (C) 2017  Dag Robole
//
//  This program is free software: you can redistribute it and/or modify
//  it under the terms of the GNU General Public License as published by
//  the Free Software Foundation, either version 3 of the License, or
//  (at your option) any later version.
//
//  This program is distributed in the hope that it will be useful,
//  but WITHOUT ANY WARRANTY; without even the implied warranty of
//  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
//  GNU General Public License for more details.
//
//  You should have received a copy of the GNU General Public License
//  along with this program.  If not, see <http://www.gnu.org/licenses/>.

#ifndef SCENE_H
#define SCENE_H

#include "session.h"
#include <QColor>
#include <QVector3D>
#include <Qt3DExtras/Qt3DWindow>
#include <Qt3DCore/QEntity>
#include <Qt3DRender/QObjectPicker>

Qt3DCore::QEntity* createScene(Qt3DExtras::Qt3DWindow *win);

Qt3DCore::QEntity* createGrid(unsigned int count,
                              float interval,
                              const QColor &color,
                              Qt3DCore::QEntity* parent);

Qt3DCore::QEntity* createSpectrum(QString name,
                                  const QVector3D &pos,
                                  const QColor &color,
                                  Qt3DCore::QEntity *parent);

Qt3DRender::QObjectPicker *createPicker(Qt3DCore::QEntity* parent);

#endif // SCENE_H
