//  gamma-analyzer-3d - 3d visualization of sessions generated by gamma-analyzer
//  Copyright (C) 2017  Dag Robole
//
//  This program is free software: you can redistribute it and/or modify
//  it under the terms of the GNU General Public License as published by
//  the Free Software Foundation, either version 3 of the License, or
//  (at your option) any later version.
//
//  This program is distributed in the hope that it will be useful,
//  but WITHOUT ANY WARRANTY; without even the implied warranty of
//  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
//  GNU General Public License for more details.
//
//  You should have received a copy of the GNU General Public License
//  along with this program.  If not, see <http://www.gnu.org/licenses/>.

#ifndef SPECTRUM_H
#define SPECTRUM_H

#include <QString>
#include <QVector>
#include <QList>

class Spectrum
{
public:
    Spectrum();
    ~Spectrum();

    bool load(QString filename);

    int sessionIndex;
    double latitudeStart, latitudeStartErr;
    double latitudeEnd, latitudeEndErr;
    double longitudeStart, longitudeStartErr;
    double longitudeEnd, longitudeEndErr;
    double altitudeStart, altitudeStartErr;
    double altitudeEnd, altitudeEndErr;
    double gpsSpeedStart, gpsSpeedStartErr;
    double gpsSpeedEnd, gpsSpeedEndErr;
    QString gpsTimeStart, gpsTimeEnd;
    int realtime, livetime;
    int totalCount;
    int numChannels;
    QVector<int> channels;

private:
};

#endif // SPECTRUM_H
