//  gamma-analyzer-3d - 3d visualization of sessions generated by gamma-analyzer
//  Copyright (C) 2017  Dag Robole
//
//  This program is free software: you can redistribute it and/or modify
//  it under the terms of the GNU General Public License as published by
//  the Free Software Foundation, either version 3 of the License, or
//  (at your option) any later version.
//
//  This program is distributed in the hope that it will be useful,
//  but WITHOUT ANY WARRANTY; without even the implied warranty of
//  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
//  GNU General Public License for more details.
//
//  You should have received a copy of the GNU General Public License
//  along with this program.  If not, see <http://www.gnu.org/licenses/>.

#include "spectrum.h"
#include <stdexcept>
#include <QJsonDocument>
#include <QJsonObject>
#include <QFile>

namespace gamma
{

Spectrum::Spectrum(QString filename)
{
    load(filename);
}

void Spectrum::load(QString filename)
{    
    QFile jsonFile(filename);
    if(!jsonFile.open(QFile::ReadOnly))
        throw std::runtime_error(
                "Spectrum::load: Unable to load JSON document " +
                filename.toStdString());

    auto doc = QJsonDocument().fromJson(jsonFile.readAll());
    if(!doc.isObject())
        throw std::runtime_error(
                "Spectrum::load: JSON document is not an object " +
                filename.toStdString());

    auto obj = doc.object();
    if(!obj.contains("arguments"))
        throw std::runtime_error(
                "Spectrum::load: Not a valid spectrum " +
                filename.toStdString());

    auto args = obj.value("arguments").toObject();

    latitudeStart = args.value("latitude_start").toDouble();
    latitudeEnd = args.value("latitude_end").toDouble();
    longitudeStart = args.value("longitude_start").toDouble();
    longitudeEnd = args.value("longitude_end").toDouble();
    altitudeStart = args.value("altitude_start").toDouble();
    altitudeEnd = args.value("altitude_end").toDouble();    
}

} // namespace gamma
